services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_duration_statement=100", "-c", "logging_collector=on", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # For Native Linux or Mac
      DATABASE_URL: postgresql://bookstore:password@db:5432/bookstore
      # FIXED: Use gateway IP instead of 'db' hostname for WSL2 compatibility and not receiving timeout
      # DATABASE_URL: postgresql://bookstore:password@172.18.0.1:5432/bookstore
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - ./scripts:/app/scripts
    command: python app.py

volumes:
  postgres_data:
